# ?????? ?? ??

server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reptile?autoReconnect=true
    username: user_reptile
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode : HTML5
#  mvc:
#    static-path-patten: classpath:/static/**
